### ISSUE TITLE
Header and Footer

### ISSUE THREAD

**Issue by gumbey** [gumbey/bluevoice#20]
@chan0345 

Remove the sub nav for films. As it's not going to be used
`<ul class="sub-menu kilo">
                  <li><a href="{{site.baseurl}}">Dolphins</a></li>
                  <li><a href="{{site.baseurl}}">Humpback Whales</a></li>
                  <li><a href="{{site.baseurl}}">Manta Rays</a></li>
                  <li><a href="{{site.baseurl}}">Orcas</a></li>
                  <li><a href="{{site.baseurl}}">Sealions</a></li>
                  <li><a href="{{site.baseurl}}">Sharks</a></li>
                  <li><a href="{{site.baseurl}}">Whales</a></li>
                </ul>`

add a a z-index of 1 to sub-menu class in main to get the nav to sit above all the content on the site.

**Comment by chan0345** [comment]
Added z-index of 2
