### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by chan0345** [gumbey/bluevoice#28]
Goal:
- [x] Finish Login Page

Tasks:
- [x] Create 'login' branch
- [x] Login form
- [x] Login with social media
- [x] Successful login page

Notes: 
• I've assigned myself, but if someone else wants to do it, feel free to assign yourself and let me know that you're working on it
• Tiffany was the one who suggested that login is usually linked with social media

**Comment by elisak** [comment]
someone please put in the social icon for the btn. I've created the buttons already, all it needs it the proper colours, and the social icons.

**Comment by gumbey** [comment]
There doesn't need to be any social Media log-ins. This is a admin Log-in only.

Just need a standard log-in field

**Comment by gumbey** [comment]
Login page done
