### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by gumbey** [gumbey/bluevoice#8]
@elgh0019 

Goal:
- [x] Passes all verification.

For Sunday:
- [x] Browser test
- [x] Code verification
- [x] Accessibility testing

Make issues on all your findings
Follow this check list by Thomas - https://learn-the-web.algonquindesign.ca/topics/launch-checklist-web-dev-4/

This goes for everyone as well
@elisak @grantjeffery @chan0345

**Comment by elisak** [comment]
the login on the footer needs fixing . it's above and off from the donate btn

**Comment by gumbey** [comment]
Done
